name: 'Deploy with issue reactions'
description: 'Action to create a deployment confirmation step'
author: 'kujiraOo'
inputs:
  githubToken:
    description: 'Github token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
